version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - DB_VENDOR=mssql
      - DB_ADDR=fizjoserver.database.windows.net
      - DB_DATABASE=FizjoDB
      - DB_USER=fizjoAdmin
      - DB_PASSWORD=Kolo1212
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - JAVA_OPTS_APPEND=-Dkeycloak.profile.feature.upload_scripts=enabled
      - KC_DB=mssql
      - KC_DB_URL=jdbc:sqlserver://fizjoserver.database.windows.net:1433;database=FizjoDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      - KC_DB_USERNAME=fizjoAdmin
      - KC_DB_PASSWORD=Kolo1212
    ports:
      - "82:8080"
    volumes:
      - ./themes:/opt/jboss/keycloak/themes
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: >
      start-dev
      --import-realm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth"]
      interval: 30s
      timeout: 10s
      retries: 3
